### ISSUE TITLE
Can you add dependencies to ripgrep-all?

### ISSUE THREAD

**Issue by phiresky** [jonasw234/au-packages#1]
Hey, author of ripgrep-all here. This repo was mentioned to me here: https://github.com/phiresky/ripgrep-all/issues/45

Currently ripgrep-all bundles some dependencies in the Windows download - this is fragile and also makes Windows builds much more annoying than they should be. I'm wondering if if I push a new version that contains only the `rga` and `rga-preproc` binaries, could you update the chocolatey package to add all the dependencies, and would that work without problems? Currently ripgrep pandoc poppler ffmpeg i think. Then I could just refer Windows users to chocolatey instead of trying to publish huge zip files.

**Comment by jonasw234** [comment]
Hey,

yes, I think that’s a good idea! It seems like all your dependencies are in the chocolatey repositories, so I’ll prepare a patch to include them as dependencies asap.

**Comment by phiresky** [comment]
Ah one more thing, the homebrew maintainers actually only added ripgrep as a dependency since in theory the other dependencies are optional (and homebrew doesn't have a method for specifying optional dependencies). In my opinion you should just add all things that make ripgrep-all more useful as dependencies, but I don't know what common practice is in chocolatey.

Also, no rush, since Windows builds are currently broken for me since travis-ci is doing weird things.

**Comment by jonasw234** [comment]
Honestly I’m rather new to building chocolatey packages myself, but from what I’ve seen it’s common practice to include all optional dependencies.

It’s just a few lines, so I just pushed a new version that will be automatically pushed to the chocolatey repositories as soon as the new Windows version is released (as long as my AppVeyor builds are not broken as well :))

**Comment by phiresky** [comment]
New version is released. @jonasw234 could you verify everything works? https://github.com/phiresky/ripgrep-all/releases

**Comment by jonasw234** [comment]
I had to update the update check for the new naming scheme (additional “v” at the beginning of the version and extension changed from “7z” to “zip”), so thanks for letting me know about the update or I might have not caught it :)
I just ran a quick test searching through my PDFs and it seems to have worked. Does the `--rga-list-adapters` check if the adapters are available or does it only list possible adapters?

**Comment by phiresky** [comment]
Thanks. list-adapters currently only lists possible adapters, it doesn't check whether they are available or not.
