### ISSUE TITLE
Are these packages still maintained?

### ISSUE THREAD

**Issue by dreamflasher** [jonasw234/au-packages#10]
For czkawka (https://community.chocolatey.org/packages/czkawka/) the CRC has been failing since the last update, and there has not been any response in the discussion by the author for 3 months. 

Could you please fix the package?

**Comment by jonasw234** [comment]
Should be fixed in https://github.com/jonasw234/au-packages/commit/82b43e02e5b61fc522dd57409f41c40a604ced82. I don’t receive notifications from Chocolatey, so Github is the place to contact me about issues with any of the packages.

**Comment by dreamflasher** [comment]
Great, thanks, that's good to know! I guess the expectation for chocolatey packages is that the communication happens on chocolatey – but I am thankful for your fast reaction and fix and that you are maintaining the packages, thank you for your work!

**Comment by virtaj** [comment]
I was able to manually select updated package.

> choco.exe install czkawka --version 6.1.0-fixed

 Default is still 6.1 which is broken. And chocolatey tries to "update" from 6.1-fixed to 6.1.

**Comment by dreamflasher** [comment]
I can confirm, that also 6.0 tries to upgade to 6.1 and not 6.1-fixed. Best would be to replace 6.1 as it's broken, or create a 6.1.1

**Comment by jonasw234** [comment]
Thanks for letting me know. Unfortunately there is no easy way to pull already published versions of existing packages back, so I’ve just [added version 6.1.0.1](https://community.chocolatey.org/packages/czkawka/6.1.0.1) (Czkawka has used x.y.z versions in the past). Hopefully this fixes things and sorry for the trouble!
