### ISSUE TITLE
Obsidian outdated

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [jonasw234/au-packages#14]
Obsidian v1.6.5 is available

**Comment by jonasw234** [comment]
Thanks for the heads-up!
New version pushed to Chocolatey and the updater script should be fixed in https://github.com/jonasw234/au-packages/commit/7cf5a412275f206a8ee9a34d333b412b61a59366 as well.
Unfortunately it looks like Obsidian silently dropped their x86 support.

**Comment by TheCakeIsNaOH** [comment]
Thank for the quick update.
