### ISSUE TITLE
w10privacy is outdated

### ISSUE THREAD

**Issue by nfriese** [jonasw234/au-packages#2]
Hi @jonasw234 ,

your package is outdated:

The error log from terminal:
> Error - hashes do not match. Actual value was 'B59BEF1F4FF0C5923BB3B5D83A9E402EF04740F481E83A9C30B26711A7C72B6D'.
> Downloading W10Privacy 64 bit
>   from 'https://sf91b3285d9193eec.jimcontent.com/download/version/1580729393/module/12302828636/name/W10Privacy.zip'
> Progress: 100% - Completed download of C:\Users\Username\AppData\Local\Temp\chocolatey\w10privacy\3.4.0.1\W10Privacy.zip (2.3 MB).
> Download of W10Privacy.zip (2.3 MB) completed.
> Error - hashes do not match. Actual value was 'B59BEF1F4FF0C5923BB3B5D83A9E402EF04740F481E83A9C30B26711A7C72B6D'.
> ERROR: Checksum for 'C:\Users\Username\AppData\Local\Temp\chocolatey\w10privacy\3.4.0.1\W10Privacy.zip' did not meet '8F490E5E2A8AEB82544A44001D44576610D7D4B0ED9388B36CBA20858874E1C2' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
> The install of w10privacy was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\w10privacy\tools\chocolateyInstall.ps1'.
>  See log for details.
> 
> Chocolatey installed 0/1 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  - w10privacy (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\w10privacy\tools\chocolateyInstall.ps1'.

The software vendor  write  his website [https://www.w10privacy.de/deutsch-start/download/](https://www.w10privacy.de/deutsch-start/download/)

> W10Privacy (contains the following languages: German, English, French, Polish, Spanish, Russian and Turkish)
> **Aktuelle Version / current version: v.3.4.0.2**
> Windows 10 / Windows 8 / Windows 7
> ________________________________________
> SHA256-Hash (of the file W10Privacy.zip): b59bef1f4ff0c5923bb3b5d83a9e402ef04740f481e83a9c30b26711a7c72b6d
> ________________________________________
> W10Privacy.zip
> Komprimiertes Archiv im ZIP Format 2.3 MB
> https://www.w10privacy.de/app/download/12302828636/W10Privacy.zip?t=1586771754

Please update the package w10privacy.

Best regards,
nfriese

**Comment by jonasw234** [comment]
Thanks for letting me know, I’ll try to fix it tomorrow.

**Comment by jonasw234** [comment]
Okay, lots of fighting with the W10Privacy installer later (it’s a EXE installer inside a ZIP package which Chocolatey doesn’t seem to like very much), I’ve uploaded a new version and asked the Chocolatey team if I may upload a new version for their review.
Will update this issue once the package is approved.

**Comment by jonasw234** [comment]
If you want to follow the progress: https://chocolatey.org/packages/w10privacy/3.4.0.2
Unfortunately the Chocolatey team hasn’t responded to my mail yet.

**Comment by jonasw234** [comment]
I was finally able to push a new version (as it turns out their mails didn’t come through, hopefully I fixed the problem on my end for good now), you can follow the progress here: https://chocolatey.org/packages/w10privacy/3.5.0.0
Sorry for the long delay!
