### ISSUE TITLE
`watchexec` is outdated

### ISSUE THREAD

**Issue by mitranim** [jonasw234/au-packages#4]
Hello there. Nice that `watchexec` is available on Choco, but it seems to be very outdated. Would be nice to get an update.

Also, any chance of making it auto-updatable, so you don't have to actually maintain it? The idea was mentioned in https://github.com/watchexec/watchexec/issues/110, but I'm no Choco expert, no idea if that's possible.

**Comment by jonasw234** [comment]
Hi @mitranim,

the package was supposed to be automatically updated, but it seems like there is a bug in the script.
I’ll try to fix it asap, thanks for letting me know!

**Comment by jonasw234** [comment]
I just updated the updater and pushed to the Chocolatey repository. The new version should hopefully be available there soon :)
