### ISSUE TITLE
Obsidian Package on Community Repo has been Outdated for Some Time. Please Update

### ISSUE THREAD

**Issue by Miloliness** [jonasw234/au-packages#7]
Thanks for having Obsidian on the Chocolatey Community Repo! Looks like something may not be working properly in your automatic package scripts. Please fix when you can.

Thanks again for your contributions to the Chocolatey Community Repo!

**Comment by jonasw234** [comment]
Thanks for letting me know! Should be fixed with 66303fea6e6d6fe541d8816e7eabca68bf0ceb21.
