### ISSUE TITLE
New Expanso Version

### ISSUE THREAD

**Issue by jgossett** [jonasw234/au-packages#9]
There is a new Expanso version. 2.2.1. See https://github.com/espanso/espanso/releases

## Expected
Expanso 2.2.1

## Actual
Expanso 2.1.8

**Comment by jonasw234** [comment]
Should hopefully be fixed in https://github.com/jonasw234/au-packages/commit/2a9b66bc7b0ed39706ecf82cb7bb6dd52dd9b2d6
